### ISSUE TITLE
Healthcheck disk safety ignore accelerated albabackend caches

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/openvstorage-health-check#292]
## Problem description
In an accelerated albabackend objects can have a lower safety but we are not interested in those safeties.
namespaces with {albaid}_{namespaceid} can be ignored (cached objects).
 

```
CRIT - FAILED HC000 - The disk safety of 1 namespace(s) is/are ZERO: 291f4739-3321-4f53-b929-bf5283f2b1e3_000034604 with 100.00000% of its objects
```

Jan told me to use the alba get-maintenance-config which contains the prefixes of the alba ids (cache_eviction_prefix_preset_pairs).
This should help you to ignore the correct namespaces.

get-maintenance-config:
```
root@ovs01:~# alba get-maintenance-config --config arakoon://config/ovs/arakoon/ssdBackend-abm/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini --to-json
{
  "success": true,
  "result": {
    "enable_auto_repair": true,
    "auto_repair_timeout_seconds": 900.0,
    "auto_repair_disabled_nodes": [],
    "enable_rebalance": true,
    "cache_eviction_prefix_preset_pairs": {
      "291f4739-3321-4f53-b929-bf5283f2b1e3": "ssdPreset"
    },
    "redis_lru_cache_eviction": {
      "host": "172.20.20.3",
      "port": 6379,
      "key": "alba_lru_b8594b80-413a-4073-9dbd-76a4d8fef01b"
    }
  }
}
```

alba get-disk-safety outputs:

namespace with prefix (cache_eviction_prefix_preset_pairs) --> ignore
```
    {
      "namespace": "291f4739-3321-4f53-b929-bf5283f2b1e3_000008622",
      "safety": 1,
      "safety_count": 14141,
      "bucket_safety": [
        {
          "bucket": [ 4, 1, 5, 1 ],
          "count": 14141,
          "applicable_dead_osds": 0,
          "remaining_safety": 1
        }
      ]
    },
```
namespace without suffix --> check

```
    {
      "namespace": "ffc00c91-5445-4486-8b5c-9fd2c8a68d81",
      "safety": 2,
      "safety_count": 1073,
      "bucket_safety": [
        {
          "bucket": [ 8, 2, 10, 3 ],
          "count": 1073,
          "applicable_dead_osds": 0,
          "remaining_safety": 2
        }
```

### Setup
- Hyperscale

### Packages
```
ii  openvstorage                         2.7.10.1-1                      amd64        openvStorage
ii  openvstorage-backend                 1.7.10.1-1                      amd64        openvStorage Backend plugin
ii  openvstorage-backend-core            1.7.10.1-1                      amd64        openvStorage Backend plugin core
ii  openvstorage-backend-webapps         1.7.10.1-1                      amd64        openvStorage Backend plugin Web Applications
ii  openvstorage-core                    2.7.10.1-1                      amd64        openvStorage core
ii  openvstorage-hc                      1.7.10.1-1                      amd64        openvStorage Backend plugin HyperConverged
ii  openvstorage-health-check            3.2.0-fargo.3-1                 amd64        Open vStorage HealthCheck
ii  openvstorage-sdm                     1.6.10.1-1                      amd64        Open vStorage Backend ASD Manager
ii  openvstorage-webapps                 2.7.10.1-1                      amd64        openvStorage Web Applications

```

**Comment by JeffreyDevloo** [comment]
https://github.com/openvstorage/openvstorage-health-check/pull/296

**Comment by JeffreyDevloo** [comment]
Still an issue with it

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/openvstorage-health-check/pull/302

**Comment by jeroenmaelbrancke** [comment]
Still an issue with the disk-safety.

Now we receive an ok state with only 1 namespace in the backend.

```
OK - SUCCESS HC000 - All data is safe on backend hddBackend with 1 namespace(s)
```

Check the code and found that you forgot that you add the disk-safety also in the dictionary.
https://github.com/openvstorage/openvstorage-health-check/blob/6de7733b80df441298b7a15588084ee4f053e765/ovs/extensions/healthcheck/alba.py#L420

you need the length from current_disk_safety with index the calculated_disk_safety
https://github.com/openvstorage/openvstorage-health-check/blob/6de7733b80df441298b7a15588084ee4f053e765/ovs/extensions/healthcheck/alba.py#L493


Snippet of the keys and lengths:

```
In [35]: %cpaste
Pasting code; enter '--' alone on the line to stop or use Ctrl-D.
:for backend_name, policies in results.iteritems():
:    for policy_prefix, policy_details in policies.iteritems():
:        print backend_name, policy_prefix, policy_details.keys()
:        print "current_disk_safety length:", len(policy_details['current_disk_safety'])
:        print "current_disk_safety keys:", policy_details['current_disk_safety'].keys()
:        for disk_safety in policy_details['current_disk_safety'].keys():
:            print "calculated_disk_safety:", len(policy_details['current_disk_safety'][disk_safety])
:--
hddBackend 8,2 ['max_disk_safety', 'current_disk_safety']
current_disk_safety length: 1
current_disk_safety keys: [2]
calculated_disk_safety: 563
ssdBackend 4,1 ['max_disk_safety', 'current_disk_safety']
current_disk_safety length: 0
current_disk_safety keys: []

```

**Comment by JeffreyDevloo** [comment]
Not related to this issue really. Moved.
